function options = set_net_options_fixed(MiniBatchSize,MaxEpochs,InitialLearnRate,DropLearnRate,XValidation,YValidation)

checkpointPath = './nets';

if (strcmp(DropLearnRate,'yes'))
    options=trainingOptions('sgdm',...
                            'Momentum',0.9, ...
                            'LearnRateSchedule','piecewise', ...
                            'LearnRateDropFactor',0.2, ...
                            'LearnRateDropPeriod',5, ...
                            'MiniBatchSize',MiniBatchSize,...       % 64        
                            'MaxEpochs',MaxEpochs,...               % 10
                            'InitialLearnRate',InitialLearnRate,... % 0.001
                            'Shuffle','every-epoch');
%                             'ValidationData',{XValidation,YValidation},...
%                             'ValidationFrequency',20,...
%                             'Plots','training-progress'); %'CheckpointPath',checkpointPath
else
    options=trainingOptions('sgdm',...
                            'Momentum',0.9, ...
                            'MiniBatchSize',MiniBatchSize,...       % 64        
                            'MaxEpochs',MaxEpochs,...               % 10
                            'InitialLearnRate',InitialLearnRate,... % 0.001
                            'Shuffle','every-epoch');
%                             'ValidationData',{XValidation,YValidation},...
%                             'ValidationFrequency',20,...
%                             'Plots','training-progress'); %'CheckpointPath',checkpointPath
end